#planner_frequency : 10 #20 #10
  #recovery_behaviors: [{name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}, {name: rotate_recovery, type: rotate_recovery/RotateRecovery}, {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}] 
#recovery_behavior_enabled : false
#max_planning_retries : -1
#conservative_reset_dist : 1.0







shutdown_costmaps: false
controller_frequency: 1.6 #1.0
planner_patience: 20.0
controller_patience: 20.0
conservative_reset_dist: 1.0
planner_frequency: 2.0
oscillation_timeout: 30.0
oscillation_distance: 0.5
recovery_behavior_enabled: false
