gazebo_ros_control:
   pid_gains:
    #  left_wheel_joint: {p: 0 ,i: 0.0 ,d: 0}
    #  right_wheel_joint: {p: 0 ,i: 0.0 ,d: 0}
    left_wheel_joint: {p: 0.5 ,i: 0.01 ,d: 0.3}
    right_wheel_joint: {p: 0.5 ,i: 0.01 ,d: 0.3}
    #  shoulder_pan_joint:
    #   p: 100.0
    #   i: 0.01 
    #   d: 10.0