global_costmap:
  footprint: [[-0.2, -0.12], [-0.2, 0.12], [0.05, 0.12], [0.05, -0.12]]
  inflation_radius: 0.55
  update_frequency: 2.0
  static_map: true
  #global_frame: odom
  #robot_base_frame: base_link
  obstacle_range: 3.0
  raytrace_range: 3.5









#global_costmap:
      #footprint: [[-0.2, -0.12], [-0.2, 0.12], [0.05, 0.12], [0.05, -0.12]]
      #inflation_radius: 0.55

  #global_frame: map
  #robot_base_frame: base_footprint
  
  #update_frequency: 5.0 #2.0
  #static_map: true
      #global_frame: odom
      #robot_base_frame: base_link
      #obstacle_range: 3.0
      #raytrace_range: 3.5

  #publish_frequency: 5.0 #10.0
  #transform_tolerance: 0.5

  #static_map: true
