local_costmap:

  obstacle_range: 15.0
  raytrace_range: 15.0

  global_frame: map
  robot_base_frame: base_link #base_footprint

  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 1.0

  rolling_window: true
  width: 12.0
  height: 12.0
  resolution: 0.02
  

  map_type: costmap
  observation_sources: scan
  scan: {sensor_frame: front_lidar, data_type: LaserScan, topic: scan, marking: true, clearing: true, inf_is_valid: true}