TrajectoryPlannerROS:
  max_vel_x: 0.3 #0.2 #0.5
  min_vel_x: 0.0 #0.05
  max_vel_theta: 0.2 #2.0
  min_in_place_vel_theta: 1.0 #0.4
  #max_rotational_vel: 0.5
  acc_lim_theta: 0.4 #3.2
  acc_lim_x: 1.6 #2.5
  acc_lim_y: 0.0 #2.5
  holonomic_robot: false
  meter_scoring: true
  pdist_scale: 5.0
  gdist_scale: 0.8
  sim_time: 2.0 #3.0
  #occdist_scale: 0.01 #0.005 #10.0 #0.01 or none
  #controller_frequency: 10.0
  #dwa: true

  # Goal Tolerance Parameters
  #xy_goal_tolerance: 0.4
  #yaw_goal_tolerance: 0.4 #change