local_costmap:
  obstacle_range: 15.0 #3.0 #2.5
  raytrace_range: 15.0 #3.5 #3.0
  footprint: [[-0.2, -0.12], [-0.2, 0.12], [0.05, 0.12], [0.05, -0.12]]
  inflation_radius: 0.8 #0.55
  
  observation_sources: laser_scan_sensor
  laser_scan_sensor: 
    #sensor_frame: hokuyo_sensor
    #topic: scan
    data_type: LaserScan
    marking: true
    clearing: true
  
  #observation_sources: pointcloud2_sensor
  #pointcloud2_sensor: 
    #sensor_frame: hokuyo_sensor
    #topic: scan
  #  data_type: PointCloud2
  #  marking: true
  #  clearing: true

 

  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 10.0 #5 #2.0
  publish_frequency: 10.0 #1 #1.0
  transform_tolerance: 1.0

  rolling_window: true
  width: 12.0 #6.0
  height: 12.0 #6.0
  resolution: 0.02 #0.05
